### ISSUE TITLE
openshift-gitops hardcoded in helper-argocd appproject

### ISSUE THREAD

**Issue by tosmi** [tjungbauer/helm-charts#6]
if we would like to reuse helper-argocd for the application-gitops instance, 
the appproject will be created in the wrong namespace (openshift-gitops)

https://github.com/tjungbauer/helm-charts/blob/b713cca70170f43c5b2a6e3d6a8a198d1f737a60/charts/helper-argocd/templates/argocd-project.yaml#L8

**Comment by tosmi** [comment]
the underlying problem is that argocd-object-manager use helper-argocd. we would like to use argocd-object-manager for the application-gitops argocd instance. project are create via helper-onboarding. so it seems helper-argocd is not required when useing arcod-object-manager for applications.

**Comment by tjungbauer** [comment]
fixed in latest release: https://github.com/tjungbauer/helm-charts/releases/tag/helper-argocd-2.0.35
